spring:
  application:
    name: microservice-config-server
  #profiles:           #表示变化的文件
  # active: native   # 使用本地文件系统的存储方式来保存配置信息
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lengaoxingchen/microservice-study-config.git
server:
  port: 8888